### ISSUE TITLE
Add a config.

### ISSUE THREAD

**Issue by MagmaSlime123** [Mrthomas20121-Mods/TFC-Metalwork#3]
Allow disabling stuff we don't want or toggling compatibility for other mod's metals.

**Comment by Mrthomas20121** [comment]
won't happens. it's not like 1.12 minecraft, you can't do that anymore

**Comment by MagmaSlime123** [comment]
You can. See Configured and Catalogue. Other mods have configs as well, even the mod this is made for.

**Comment by Mrthomas20121** [comment]
I won't add config to disable metals and other stuff. 

recipes are already optionals based on if the mod is loaded.
