### ISSUE TITLE
an error in the recipe.

### ISSUE THREAD

**Issue by eagl19** [Mrthomas20121-Mods/TFC-Metalwork#5]
recipes\heating\metal\ in recipes *_(block|cut|ladder)_(slab|stairs|wall).json mistake "ingredient": {  "item": "tfc_metalwork/metal/cut/antimony_slab" }. It needs to be  {  "item": "tfc_metalwork:metal/cut/antimony_slab" }

**Comment by Mrthomas20121** [comment]
i did not notice those issues, they will be fixed
